# Generated by Django 4.2.1 on 2023-06-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='c_id',
        ),
    ]
